/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Minimal LED blink test (busy-wait) on PC13.
   Use this to verify MCU runs and LED wiring. */

#include "stm32f10x.h"
#include "stm32f10x_rcc.h"
#include "stm32f10x_gpio.h"
#include <stdlib.h>
#include "DHT11.h"

/* ms tick counter (may be referenced by SysTick handler) */
volatile uint32_t msTicks = 0;

static void delay_ms(uint32_t ms) {
  while (ms--) {
    for (volatile uint32_t i = 0; i < 8000; ++i) {
      __asm volatile ("nop");
    }
  }
}

static void delay_us(uint32_t us) {
  while (us--) {
    for (volatile uint32_t i = 0; i < 8; ++i) {
      __asm volatile ("nop");
    }
  }
}

static void DHT11_SetPinOutput(void *port, uint16_t pin, void *user_ctx) {
  GPIO_InitTypeDef gpio;
  gpio.GPIO_Pin = pin;
  gpio.GPIO_Speed = GPIO_Speed_2MHz;
  gpio.GPIO_Mode = GPIO_Mode_Out_PP;
  GPIO_Init((GPIO_TypeDef *)port, &gpio);
  GPIO_ResetBits((GPIO_TypeDef *)port, pin);
}

static void DHT11_SetPinInput(void *port, uint16_t pin, void *user_ctx) {
  GPIO_InitTypeDef gpio;
  gpio.GPIO_Pin = pin;
  gpio.GPIO_Speed = GPIO_Speed_2MHz;
  gpio.GPIO_Mode = GPIO_Mode_IPU;
  GPIO_Init((GPIO_TypeDef *)port, &gpio);
}

static uint8_t DHT11_ReadPin(void *port, uint16_t pin, void *user_ctx) {
  return GPIO_ReadInputDataBit((GPIO_TypeDef *)port, pin) ? 1 : 0;
}

static void InitGPIOPorts(void) {
  RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB | RCC_APB2Periph_GPIOC, ENABLE);

  GPIO_InitTypeDef gpio;

  gpio.GPIO_Pin = GPIO_Pin_13;
  gpio.GPIO_Speed = GPIO_Speed_2MHz;
  gpio.GPIO_Mode = GPIO_Mode_Out_PP;
  GPIO_Init(GPIOC, &gpio);
}

int main(void) {
  uint8_t temperature = 0;
  uint8_t humidity = 0;
  int result;

  InitGPIOPorts();

  DHT11_Config_t dht11 = {
      .port = GPIOB,
      .pin = GPIO_Pin_0,
      .status = 0,
      .delay_us = delay_us,
      .set_pin_output = DHT11_SetPinOutput,
      .set_pin_input = DHT11_SetPinInput,
      .read_pin = DHT11_ReadPin,
      .user_ctx = NULL,
  };

  DHT11_Init(&dht11);

  while (1) {
    result = DHT11_Read(&dht11, &temperature, &humidity);
    if (result == 0) {
      /* Blink LED once when read succeeds. */
      GPIO_ResetBits(GPIOC, GPIO_Pin_13);
      delay_ms(200);
      GPIO_SetBits(GPIOC, GPIO_Pin_13);
    } else {
      /* Longer blink on error. */
      GPIO_ResetBits(GPIOC, GPIO_Pin_13);
      delay_ms(500);
      GPIO_SetBits(GPIOC, GPIO_Pin_13);
      delay_ms(500);
    }

    delay_ms(1000);
  }

  return 0;
}
